apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
    app: myapp
    tier: frontend
    env: test
spec:
  selector:
    matchLabels:
      env: test
  replicas: 3
  template:
    metadata:
      name:  nginx
      labels: 
        name: myapp
        tier: frontend
        env: test
    spec:
      containers:
        - name:  myapp-nginx1
          image:  nginx

